name: "File"
description: "Files GitHub issues to track potential accessibility gaps."

inputs:
  findings:
    description: "List of potential accessibility gaps, as stringified JSON"
    required: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Token with fine-grained permission 'issues: write'"
    required: true
  cached_filings:
    description: "Cached filings from previous runs, as stringified JSON. Without this, duplicate issues may be filed."
    required: false
  screenshot_repository:
    description: "Repository (with owner) where screenshots are stored on the gh-cache branch. Defaults to the 'repository' input if not set. Required if issues are open in a different repo to construct proper screenshot URLs."
    required: false
  open_grouped_issues:
    description: "In the 'file' step, also open grouped issues which link to all issues with the same root cause"
    required: false
    default: "false"

outputs:
  filings:
    description: "List of issues filed (and their associated finding(s)), as stringified JSON"

runs:
  using: "node24"
  main: "bootstrap.js"

branding:
  icon: "compass"
  color: "blue"
