name: "File"
description: "Files GitHub issues to track potential accessibility gaps."

inputs:
  findings:
    description: "List of potential accessibility gaps, as stringified JSON"
    required: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Token with fine-grained permission 'issues: write'"
    required: true
  cached_findings:
    description: "Cached findings from previous runs, as stringified JSON. Without this, duplicate issues may be filed."
    required: false

outputs:
  findings:
    description: "List of potential accessibility gaps (plus issue URLs), as stringified JSON"
  closed_issues:
    description: "List of closed issues, as stringified JSON"
  opened_issues:
    description: "List of newly-opened issues, as stringified JSON"
  repeated_issues:
    description: "List of repeated issues, as stringified JSON"
  closed_issue_urls:
    description: "DEPRECATED: List of URLs for closed issues, as stringified JSON"
  opened_issue_urls:
    description: "DEPRECATED: List of URLs for newly-opened issues, as stringified JSON"
  repeated_issue_urls:
    description: "DEPRECATED: List of URLs for repeated issues, as stringified JSON"

runs:
  using: "node20"
  main: "bootstrap.js"

branding:
  icon: "compass"
  color: "blue"