name: "continuous-ai-for-accessibility-scanner"
description: "Finds potential accessibility gaps, files GitHub issues to track them, and attempts to fix them with Copilot."

inputs:
  urls:
    description: "Newline-delimited list of URLs to check for accessibility issues"
    required: true
    multiline: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Personal access token (PAT) with fine-grained permissions 'contents: write', 'issues: write', and 'pull_requests: write'"
    required: true
  cache_key:
    description: "Custom key for caching findings across runs"
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate cache key
      id: cache_key
      shell: bash
      run: |
        CACHE_KEY="${{ inputs.cache_key }}"
        if [[ -z "$CACHE_KEY" ]]; then
          # If cache_key is not provided, generate a default one using the branch name, replacing characters (e.g. `/`) which would create unexpected paths.
          CACHE_KEY=$(printf 'cached_findings-%s' "${{ github.ref_name }}" | tr -cs 'A-Za-z0-9._-' '_')
        fi
        echo "cache_key=$CACHE_KEY" >> $GITHUB_OUTPUT
    - name: Restore cached_findings
      id: restore
      uses: ./.github/actions/gh-cache/cache
      with:
        key: ${{ steps.cache_key.outputs.cache_key }}
        token: ${{ inputs.token }}
    - name: Find
      id: find
      uses: ./.github/actions/find
      with:
        urls: ${{ inputs.urls }}
    - name: File
      id: file
      uses: ./.github/actions/file
      with:
        findings: ${{ steps.find.outputs.findings }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        cached_findings: ${{ steps.restore.outputs.value }}
    - name: Fix
      id: fix
      uses: ./.github/actions/fix
      with:
        issue_urls: ${{ steps.file.outputs.opened_issue_urls }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
    - name: Save cached_findings
      uses: ./.github/actions/gh-cache/cache
      with:
        key: ${{ steps.cache_key.outputs.cache_key }}
        value: ${{ steps.file.outputs.findings }}
        token: ${{ inputs.token }}

branding:
  icon: "compass"
  color: "blue"