name: "Fix"
description: "Attempts to fix issues with Copilot."

inputs:
  issues:
    description: "List of issues to attempt to fix, as stringified JSON"
    required: false
  issue_urls:
    description: "List of issue URLs to attempt to fix, as stringified JSON"
    required: false
  repository:
    description: "Repository (with owner) containing issues"
    required: true
  token:
    description: "Personal access token (PAT) with fine-grained permissions 'issues: write' and 'pull_requests: write'"
    required: true

runs:
  using: "node24"
  main: "bootstrap.js"

branding:
  icon: "compass"
  color: "blue"
